const getters = {
  // sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  // device: state => state.app.device,
  // visitedViews: state => state.tagsView.visitedViews,
  // cachedViews: state => state.tagsView.cachedViews,
  getUser: state => state.routemap.getUser,
  // avatar: state => state.user.avatar,
  // name: state => state.user.name,
  // introduction: state => state.user.introduction,
  // status: state => state.user.status,
  // roles: state => state.user.roles,
  // setting: state => state.user.setting,
  // permission_routers: state => state.permission.routers,
  // addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,
  allbackNew: state => state.routemap.allbackNew, // 初始化数据
  shipImo: state => state.routemap.shipImo, // 设置imo
  isSetCenter: state => state.routemap.isSetCenter,
  minimizeWindows: state => state.routemap.minimizeWindows, // 最小化窗口
  shipInfos: state => state.routemap.shipInfos, // 船详情缓存数据
  reachPortSearch: state => state.routemap.reachPortSearch, // 历史航速
  shipHallSearch: state => state.routemap.shipHallSearch, // 船盘大厅搜索
  allShipPlateList: state => state.routemap.allShipPlateList, // 船盘大厅所有
  portListAll: state => state.routemap.portListAll, // 港口数据
  getPortListAllInit: state => state.routemap.getPortListAllInit, // 初始化港口数据
  shipHallFile: state => state.routemap.shipHallFile, // 船舶档案查询
  shipHallCondition: state => state.routemap.shipHallCondition, // 船舶档案查询条件
  getPortFlag: state => state.routemap.getPortFlag,
  currentPort: state => state.routemap.currentPort, // 当前在港
  expectedPorts: state => state.routemap.expectedPort, // 预计到港
  historyPorts: state => state.routemap.historyPort, // 历史到港
  historyCourse: state => state.routemap.historyCourse, // 历史航线
  settingPageVisible: state => state.routemap.settingPageVisible,
  setVlessInfo: state => state.routemap.setVlessInfo, // 船舶档案
  getWeatherShow: state => state.routemap.getWeatherShow, // 船舶详情天气
  getPortName: state => state.routemap.getPortName, // 缓存港口name
  gethistoryportDate: state => state.routemap.gethistoryportDate, // 历史航线数据缓存
  getQueeryFleets: state => state.routemap.getQueeryFleets, // 船队
  deleteImo: state => state.routemap.deleteImo // 删除改变船队状态
}
export default getters
